// WARNING: DO NOT EDIT THIS FILE, IT IS AUTOGENERATED
module.exports = {
  addonType: "effect",
  id: "skymen_film_grain",
  name: "film_grain",
  version: "1.0.0.0",
  category:
    // "blend",
    // "distortion",
    // "normal-mapping",
    // "tiling",
    // "other",
    "color",
  author: "skymen",
  website: "https://www.construct.net",
  documentation: "https://www.construct.net",
  description: "Adds a cinematic film grain effect.",
  supportedRenderers: ["webgl", "webgl2", "webgpu"],
  blendsBackground: false,
  usesDepth: false,
  crossSampling: false,
  preservesOpaqueness: true,
  animated: false,
  mustPredraw: false,
  extendBox: {
    horizontal: 0,
    vertical: 0,
  },
  isDeprecated: false,
  parameters: [
    /*
    {
      type:
        "float"
        "percent"
        "color"
      ,
      id: "property_id",
      value: 0,
      uniform: "uPropertyId",
      // precision: "lowp" // defaults to lowp if omitted
      interpolatable: true,
      name: "Property Name",
      desc: "Property Description",
    }
    */
    {
      type: "float",
      id: "strength",
      value: 16,
      uniform: "uStrength",
      interpolatable: true,
      name: "Strength",
      desc: "Strength",
    },
    {
      type: "percent",
      id: "add_or_multiply",
      value: 0,
      uniform: "uAddOrMultiply",
      interpolatable: true,
      name: "Add or Multiply",
      desc: "0: Add, 1: Multiply",
    },
  ],
};
